In [5]:
!pip3 install torch

In [0]:
import torch
import numpy as np

In [14]:
v = torch.tensor([1,2,3,4,5,6])
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [27]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.type())

torch.FloatTensor


In [22]:
v.view(2,-1 )

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [29]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
