In [0]:
import torch
from torch.nn import Linear

In [7]:
torch.manual_seed(1)
model = Linear(in_features=2, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.1371], requires_grad=True) Parameter containing:
tensor([[ 0.3643, -0.3121]], requires_grad=True)


In [9]:
x = torch.tensor([[2.0, 3.0], [1.0, 2.0]])
model(x)

tensor([[-0.3447],
        [-0.3969]], grad_fn=<AddmmBackward>)